const drugs = [
    {
      id: 'paracetamol',
      name: 'پاراستامول (استامینوفن)',
      form: 'قرص',
      commonDose: '500–1000میلی‌گرم هر 4–6 ساعت',
      usage: 'خوراکی، بعد غذا یا با معده خالی',
      indications: 'تب، دردهای خفیف تا متوسط',
      contraindications: 'حساسیت به دارو',
      interactions: 'الکل، وارفارین',
      sideEffects: 'حالت تهوع، بثورات پوستی',
      pregnancy: 'قابل مصرف در بارداری و شیردهی با احتیاط',
      formula: '10-15 mg/kg/dose',
      maxDose: '1000 mg',
      frequency: 'هر 4-6 ساعت',
      source: 'WHO Guidelines 2023',
      maxDaily: '4000 mg',
      category: 'مسکن و تب کاهنده',
      dividedDose: 'هر 4-6 ساعت یک بار',
    },
    {
      id: 'ibuprofen',
      name: 'ایبوپروفن',
      form: 'قرص',
      commonDose: '400میلی‌گرم هر 6–8 ساعت',
      usage: 'خوراکی، همراه غذا',
      indications: 'درد، تب، التهاب مفاصل',
      contraindications: 'زخم معده، نارسایی کلیوی',
      interactions: 'آسپرین، وارفارین',
      sideEffects: 'سوزش معده، تهوع',
      pregnancy: 'فقط با تجویز در بارداری مصرف شود',
      formula: '5-10 mg/kg/dose',
      maxDose: '400 mg',
      frequency: 'هر 6-8 ساعت',
      source: 'AAP 2022',
      maxDaily: '1200 mg',
      category: 'مسکن و ضدالتهاب',
      dividedDose: 'هر 6-8 ساعت یک بار',
    },
    {
      id: 'diphenhydramine',
      name: 'دیفن‌هیدرامین',
      form: 'شربت',
      commonDose: '25–50میلی‌گرم هر 6–8 ساعت',
      usage: 'خوراکی، قبل از خواب ترجیحاً',
      indications: 'آلرژی، خارش، بی‌خوابی',
      contraindications: 'گلوکوم، بزرگی پروستات',
      interactions: 'الکل، داروهای خواب‌آور',
      sideEffects: 'خواب‌آلودگی، خشکی دهان',
      pregnancy: 'خیر',
      formula: '1-2 mg/kg/dose',
      maxDose: '50 mg',
      frequency: 'هر 6-8 ساعت',
      source: 'Lexicomp 2023',
      maxDaily: '150 mg',
      category: 'آنتی هیستامین',
      dividedDose: 'هر 6-8 ساعت یک بار',
    },
    {
      id: 'famotidine',
      name: 'فاموتیدین',
      form: 'قرص',
      commonDose: '20میلی‌گرم دو بار در روز',
      usage: 'خوراکی، قبل غذا',
      indications: 'رفلاکس معده، سوزش سر دل',
      contraindications: 'حساسیت به دارو',
      interactions: 'کتوکونازول، آتازاناویر',
      sideEffects: 'سردرد، یبوست',
      pregnancy: 'بله',
      formula: '0.2-0.4 mg/kg/day',
      maxDose: '40 mg',
      frequency: 'هر 12 ساعت',
      source: 'UpToDate 2023',
      maxDaily: '80 mg',
      category: 'داروی معده',
      dividedDose: 'هر 12 ساعت یک بار (2 بار در روز)',
    },
    {
      id: 'pseudoephedrine',
      name: 'کلداکس (سودوافدرین)',
      form: 'کپسول',
      commonDose: '250 میلی‌گرم روزی یک بار',
      usage: 'خوراکی، با آب کافی',
      indications: 'سرماخوردگی، احتقان بینی',
      contraindications: 'فشار خون بالا، دیابت',
      interactions: 'مهارکننده MAO',
      sideEffects: 'خشکی دهان، گیجی',
      pregnancy: 'خیر',
      formula: '1-2 mg/kg/day',
      maxDose: '60 mg',
      frequency: 'هر 6-8 ساعت',
      source: 'Sanford Guide 2023',
      maxDaily: '180 mg',
      category: 'دکونژستانت',
      dividedDose: 'هر 6-8 ساعت یک بار',
    },
    {
      id: 'zinc',
      name: 'زینک پلاس',
      form: 'قرص',
      commonDose: '500 میلی‌گرم روزی یک بار',
      usage: 'خوراکی، بعد از غذا',
      indications: 'تقویت سیستم ایمنی، ریزش مو',
      contraindications: 'حساسیت به زینک',
      interactions: 'آنتی‌بیوتیک‌ها',
      sideEffects: 'معده‌درد، تهوع',
      pregnancy: 'بله',
      formula: '1-2 mg/kg/day',
      maxDose: '40 mg',
      frequency: 'روزانه',
      source: 'NIH Guidelines 2023',
      maxDaily: '40 mg',
      category: 'مکمل',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'vitamin_c',
      name: 'ویتامین C جوشان',
      form: 'قرص',
      commonDose: '500 میلی‌گرم روزی یک بار',
      usage: 'در یک لیوان آب حل شود',
      indications: 'تقویت سیستم ایمنی، پیشگیری از سرماخوردگی',
      contraindications: 'سنگ کلیه اگزالاتی',
      interactions: 'آسپرین، شیمی‌درمانی',
      sideEffects: 'اسهال، تهوع',
      pregnancy: 'بله',
      formula: '10-20 mg/kg/day',
      maxDose: '1000 mg',
      frequency: 'روزانه',
      source: 'NIH Guidelines 2023',
      maxDaily: '1000 mg',
      category: 'مکمل',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'vitamin_d',
      name: 'ویتامین D3',
      form: 'قرص',
      commonDose: '500 میلی‌گرم روزی یک بار',
      usage: 'خوراکی، بعد غذا',
      indications: 'کمبود ویتامین D، تقویت استخوان',
      contraindications: 'هایپرکلسمی',
      interactions: 'دیگوکسین',
      sideEffects: 'یبوست، تهوع',
      pregnancy: 'بله',
      formula: '400-800 IU/day',
      maxDose: '4000 IU',
      frequency: 'روزانه',
      source: 'Endocrine Society 2023',
      maxDaily: '4000 IU',
      category: 'مکمل',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'bisacodyl',
      name: 'بیزاکودیل',
      form: 'قرص',
      commonDose: '5–10میلی‌گرم روزانه',
      usage: 'خوراکی یا رکتال',
      indications: 'یبوست موقت',
      contraindications: 'انسداد روده، آپاندیسیت',
      interactions: 'دیورتیک‌ها',
      sideEffects: 'درد شکم، اسهال',
      pregnancy: 'خیر',
      formula: '0.1-0.2 mg/kg/day',
      maxDose: '10 mg',
      frequency: 'روزانه',
      source: 'Lexicomp 2023',
      maxDaily: '10 mg',
      category: 'لاغری و یبوست',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'loratadine',
      name: 'لوراتادین',
      form: 'قرص',
      commonDose: '10میلی‌گرم در روز',
      usage: 'خوراکی، با یا بدون غذا',
      indications: 'حساسیت فصلی، خارش، کهیر',
      contraindications: 'بیماری کبدی شدید',
      interactions: 'الکل، سایمتیدین',
      sideEffects: 'سردرد، خواب‌آلودگی',
      pregnancy: 'بله',
      formula: '0.2-0.4 mg/kg/day',
      maxDose: '10 mg',
      frequency: 'روزانه',
      source: 'UpToDate 2023',
      maxDaily: '10 mg',
      category: 'آنتی هیستامین',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'antihistamine_decongestant',
      name: 'آنتی هیستامین دکونژستانت',
      form: 'شربت',
      commonDose: '5میلی‌لیتر هر 6–8 ساعت',
      usage: 'خوراکی، بعد غذا',
      indications: 'احتقان بینی، آلرژی',
      contraindications: 'فشار خون بالا',
      interactions: 'MAOI',
      sideEffects: 'گیجی، خواب‌آلودگی',
      pregnancy: 'خیر',
      formula: '0.5-1 mg/kg/day',
      maxDose: '15 ml',
      frequency: 'هر 6-8 ساعت',
      source: 'AAP 2023',
      maxDaily: '45 ml',
      category: 'ترکیبی',
      dividedDose: 'هر 6-8 ساعت یک بار',
    },
    {
      id: 'betamethasone_topical',
      name: 'بتامتازون موضعی',
      form: 'پماد',
      commonDose: 'طبق دستور پزشک با توجه به وزن یا وضعیت بیمار',
      usage: 'موضعی',
      indications: 'التهاب‌های پوستی، اگزما',
      contraindications: 'عفونت قارچی',
      interactions: 'داروهای تضعیف ایمنی',
      sideEffects: 'سوزش، خشکی پوست',
      pregnancy: 'با احتیاط',
      formula: '0.1-0.2 mg/kg/day',
      maxDose: '5 mg',
      frequency: 'روزانه',
      source: 'Dermatology Guidelines 2023',
      maxDaily: '5 mg',
      category: 'کورتیکواستروئید موضعی',
      dividedDose: 'دو بار در روز',
    },
    {
      id: 'aloe_vera_gel',
      name: 'آلوئه‌ورا ژل',
      form: 'ژل موضعی',
      commonDose: 'مقداری نازک بمالید 2–3 times daily',
      usage: 'موضعی',
      indications: 'سوختگی، آفتاب‌سوختگی',
      contraindications: 'زخم باز',
      interactions: 'ندارد',
      sideEffects: 'سوزش موقتی',
      pregnancy: 'بله',
      formula: 'طبق نیاز',
      maxDose: 'طبق نیاز',
      frequency: 'بر اساس نیاز',
      source: 'Herbal Medicine Guidelines 2023',
      maxDaily: 'طبق نیاز',
      category: 'طب سنتی',
      dividedDose: 'بر اساس نیاز',
    },
    {
      id: 'cetirizine',
      name: 'سیتریزین',
      form: 'قرص',
      commonDose: 'طبق دستور پزشک با توجه به وزن یا وضعیت بیمار',
      usage: 'خوراکی',
      indications: 'آلرژی، کهیر',
      contraindications: 'نارسایی کلیوی',
      interactions: 'الکل',
      sideEffects: 'خواب‌آلودگی، خشکی دهان',
      pregnancy: 'بله',
      formula: '0.2-0.4 mg/kg/day',
      maxDose: '10 mg',
      frequency: 'روزانه',
      source: 'UpToDate 2023',
      maxDaily: '10 mg',
      category: 'آنتی هیستامین',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'iron_fumarate',
      name: 'آهن فومارات',
      form: 'قرص',
      commonDose: '500 میلی‌گرم روزی یک بار',
      usage: 'خوراکی، با معده خالی یا همراه غذا',
      indications: 'کم‌خونی فقر آهن',
      contraindications: 'هموکروماتوز',
      interactions: 'آنتی‌اسیدها',
      sideEffects: 'یبوست، تهوع',
      pregnancy: 'بله',
      formula: '3-6 mg/kg/day',
      maxDose: '200 mg',
      frequency: 'روزانه',
      source: 'Hematology Guidelines 2023',
      maxDaily: '200 mg',
      category: 'مکمل',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'silicone_gel',
      name: 'سیلیکون موضعی',
      form: 'ژل',
      commonDose: 'طبق دستور پزشک با توجه به وزن یا وضعیت بیمار',
      usage: 'موضعی',
      indications: 'جای زخم و اسکار',
      contraindications: 'زخم باز',
      interactions: 'ندارد',
      sideEffects: 'تحریک پوست',
      pregnancy: 'بله',
      formula: 'طبق نیاز',
      maxDose: 'طبق نیاز',
      frequency: 'روزانه',
      source: 'Plastic Surgery Guidelines 2023',
      maxDaily: 'طبق نیاز',
      category: 'مراقبت پوست',
      dividedDose: 'دو بار در روز',
    },
    {
      id: 'ors',
      name: 'ساشه ORS',
      form: 'پودر',
      commonDose: '۱ ساشه (معادل ۲۰۰ میلی‌لیتر) بعد از هر بار اسهال',
      usage: 'در آب حل شود',
      indications: 'کم‌آبی بدن، اسهال',
      contraindications: 'انسداد روده',
      interactions: 'ندارد',
      sideEffects: 'نفخ، تهوع',
      pregnancy: 'بله',
      formula: 'طبق نیاز',
      maxDose: 'طبق نیاز',
      frequency: 'بر اساس نیاز',
      source: 'WHO Guidelines 2023',
      maxDaily: 'طبق نیاز',
      category: 'الکترولیت',
      dividedDose: 'بر اساس نیاز',
    },
    {
      id: 'diphenhydramine_topical',
      name: 'دیفن هیدرامین موضعی',
      form: 'کرم',
      commonDose: 'طبق دستور پزشک با توجه به وزن یا وضعیت بیمار',
      usage: 'موضعی',
      indications: 'نیش حشرات، خارش',
      contraindications: 'گلوکوم',
      interactions: 'محلول‌های ضدخارش دیگر',
      sideEffects: 'تحریک پوست',
      pregnancy: 'با احتیاط',
      formula: 'طبق نیاز',
      maxDose: 'طبق نیاز',
      frequency: 'روزانه',
      source: 'Dermatology Guidelines 2023',
      maxDaily: 'طبق نیاز',
      category: 'آنتی هیستامین موضعی',
      dividedDose: 'سه بار در روز',
    },
    {
      id: 'petroleum_jelly',
      name: 'پماد آ.د (وازلین)',
      form: 'پماد',
      commonDose: 'طبق دستور پزشک با توجه به وزن یا وضعیت بیمار',
      usage: 'موضعی',
      indications: 'خشکی پوست، پیشگیری از سوختگی پای نوزاد',
      contraindications: 'حساسیت به وازلین',
      interactions: 'ندارد',
      sideEffects: 'واکنش آلرژیک',
      pregnancy: 'بله',
      formula: 'طبق نیاز',
      maxDose: 'طبق نیاز',
      frequency: 'روزانه',
      source: 'Skin Care Guidelines 2023',
      maxDaily: 'طبق نیاز',
      category: 'مرطوب کننده',
      dividedDose: 'دو تا سه بار در روز',
    },
    {
      id: 'lidocaine_topical',
      name: 'پماد لیدوکائین',
      form: 'کرم',
      commonDose: 'طبق دستور پزشک با توجه به وزن یا وضعیت بیمار',
      usage: 'موضعی',
      indications: 'بی‌حسی موضعی، درد بواسیر',
      contraindications: 'زخم باز',
      interactions: 'ضد آریتمی‌ها',
      sideEffects: 'سوزش موقتی',
      pregnancy: 'با احتیاط',
      formula: 'طبق نیاز',
      maxDose: 'طبق نیاز',
      frequency: 'روزانه',
      source: 'Anesthesia Guidelines 2023',
      maxDaily: 'طبق نیاز',
      category: 'بی‌حس کننده موضعی',
      dividedDose: 'سه بار در روز',
    },
    {
      id: 'paracetamol_pediatric',
      name: 'پاراستامول کودکان',
      form: 'قطره',
      commonDose: '10–15میلی‌گرم/kg هر 6 ساعت',
      usage: 'خوراکی، با سرنگ مدرج',
      indications: 'تب و درد کودکان',
      contraindications: 'حساسیت',
      interactions: 'وارفارین',
      sideEffects: 'خواب‌آلودگی',
      pregnancy: 'بله',
      formula: '10-15 mg/kg/dose',
      maxDose: '15 mg/kg',
      frequency: 'هر 6 ساعت',
      source: 'AAP 2023',
      maxDaily: '60 mg/kg',
      category: 'مسکن کودکان',
      dividedDose: 'هر 6 ساعت یک بار',
    },
    {
      id: 'fluconazole',
      name: 'فلوکونازول',
      form: 'قرص',
      commonDose: '150میلی‌گرم تک‌دوز',
      usage: 'خوراکی',
      indications: 'عفونت قارچی واژن',
      contraindications: 'نارسایی کبد',
      interactions: 'وارفارین، فنی‌توئین',
      sideEffects: 'تهوع، سردرد',
      pregnancy: 'با احتیاط',
      formula: '3-6 mg/kg/day',
      maxDose: '400 mg',
      frequency: 'روزانه',
      source: 'IDSA Guidelines 2023',
      maxDaily: '400 mg',
      category: 'آنتی فونگال',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'vitamin_b_complex',
      name: 'قرص ویتامین B کمپلکس',
      form: 'قرص',
      commonDose: '500 میلی‌گرم روزی یک بار',
      usage: 'خوراکی',
      indications: 'کمبود ویتامین B، ضعف عمومی',
      contraindications: 'حساسیت',
      interactions: 'الکل',
      sideEffects: 'ادرار زرد، تهوع',
      pregnancy: 'بله',
      formula: '1-2 mg/kg/day',
      maxDose: '100 mg',
      frequency: 'روزانه',
      source: 'NIH Guidelines 2023',
      maxDaily: '100 mg',
      category: 'مکمل',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'azelastine',
      name: 'آزلستین',
      form: 'اسپری بینی',
      commonDose: '0.1 میلی‌گرم/puff روزی دو بار',
      usage: 'استنشاقی',
      indications: 'آلرژی بینی',
      contraindications: 'رینیت باکتریایی',
      interactions: 'الکل',
      sideEffects: 'سوزش بینی',
      pregnancy: 'بله',
      formula: '0.1-0.2 mg/kg/day',
      maxDose: '0.28 mg',
      frequency: 'روزانه',
      source: 'Allergy Guidelines 2023',
      maxDaily: '0.28 mg',
      category: 'آنتی هیستامین بینی',
      dividedDose: 'دو بار در روز',
    },
    {
      id: 'calcium_carbonate',
      name: 'قرص جوشان کلسیم',
      form: 'قرص',
      commonDose: '500 میلی‌گرم روزی یک بار',
      usage: 'در آب حل شود',
      indications: 'کمبود کلسیم، پوکی استخوان',
      contraindications: 'هایپرکلسمی',
      interactions: 'دیگوکسین',
      sideEffects: 'یبوست',
      pregnancy: 'بله',
      formula: '500-1000 mg/day',
      maxDose: '1000 mg',
      frequency: 'روزانه',
      source: 'Endocrinology Guidelines 2023',
      maxDaily: '1000 mg',
      category: 'مکمل',
      dividedDose: 'یک بار در روز',
    },
    {
      id: 'amoxicillinclavulanate',
      name: 'Amoxicillin‑Clavulanate',
      form: 'قرص',
      commonDose: '500 میلی‌گرم/125 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'عفونت تنفسی، سینوزیت',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '2 g/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'آنتی‌بیوتیک',
      dividedDose: 'هر 12 ساعت',
    },
    {
      id: 'cefixime',
      name: 'Cefixime',
      form: 'قرص',
      commonDose: '400 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'عفونت ادراری، گلو',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '400 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'سفالوسپورین',
      dividedDose: 'روزی یکبار',
    },
    {
      id: 'cephalexin',
      name: 'Cephalexin',
      form: 'کپسول',
      commonDose: '500 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'پوست، ادراری',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '4 g/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'سفالوسپورین',
      dividedDose: 'هر 6 ساعت',
    },
    {
      id: 'pantoprazole',
      name: 'Pantoprazole',
      form: 'قرص',
      commonDose: '40 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'ریفلاکس، زخم معده',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '40 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'ضد اسید',
      dividedDose: 'روزی یکبار',
    },
    {
      id: 'paracetamol',
      name: 'Paracetamol',
      form: 'قرص',
      commonDose: '500 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'تب، درد خفیف',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '4000 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'مسکن OTC',
      dividedDose: 'هر 4–6 ساعت',
    },
    {
      id: 'ibuprofen',
      name: 'Ibuprofen',
      form: 'قرص',
      commonDose: '400 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'درد، التهاب',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '1200 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'NSAID OTC',
      dividedDose: 'هر 6–8 ساعت',
    },
    {
      id: 'naproxen',
      name: 'Naproxen',
      form: 'قرص',
      commonDose: '220 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'درد، قاعدگی',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '660 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'NSAID OTC',
      dividedDose: 'هر 8–12 ساعت',
    },
    {
      id: 'diclofenac',
      name: 'Diclofenac',
      form: 'قرص',
      commonDose: '50 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'التهاب مفاصل',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '150 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'NSAID',
      dividedDose: '2–3 بار در روز',
    },
    {
      id: 'azithromycin',
      name: 'Azithromycin',
      form: 'قرص',
      commonDose: '250 میلی‌گرم',
      usage: 'خوراکی',
      indications: 'عفونت تنفسی، گوش',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '500 mg/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'ماکرولید',
      dividedDose: 'روزی یکبار',
    },
    {
      id: 'ceftriaxone',
      name: 'Ceftriaxone',
      form: 'تزریقی',
      commonDose: '۱ گرم تزریقی داخل عضلانی یا وریدی',
      usage: 'تزریقی',
      indications: 'مننژیت، ذات‌الریه',
      contraindications: '',
      interactions: '',
      sideEffects: '',
      pregnancy: '',
      formula: '',
      maxDose: '4 g/day',
      frequency: '',
      source: '',
      maxDaily: '',
      category: 'سفالوسپورین تزریقی',
      dividedDose: 'روزی یکبار',
    }
  ];